### ISSUE TITLE
スクリプトの追加

### ISSUE THREAD

**Issue by BND-tc** [KMiyawaki/rsj_pointcloud_to_laserscan#1]
YVT-35LXの3次元データを2次元データに変換するスクリプトの追加をお願いいたします。

ファイル名：　rsj_pointcloud_to_laserscan_3durg.launch

[https://drive.google.com/file/d/103Y4HPMdfUfxqfD58QGTIgvC9YhKjtu7/view?usp=sharing](url)

**Comment by KMiyawaki** [comment]
ありがとうございます。追加しました。
また、Collaboratorとして登録させていただきました（招待メールが行ったと思います）。気が付かなくてすみませんでした。お手数をおかけしました。
